from django.urls import path, re_path

from aeis_dashboard import views


urlpatterns = [
    path("", views.frontend_index, name="aeis_django_home"),
    path("health", views.health, name="aeis_django_health"),
    path("api/dashboard/summary", views.dashboard_summary, name="dashboard_summary"),
    path("api/dashboard/realtime", views.dashboard_realtime, name="dashboard_realtime"),
    path("api/dashboard/county/<path:identifier>", views.dashboard_county, name="dashboard_county"),
    path("api/dashboard/alerts", views.dashboard_alerts, name="dashboard_alerts"),
    path("api/dashboard/reports", views.dashboard_reports, name="dashboard_reports"),
    path("api/weather/forecast", views.weather_forecast, name="weather_forecast"),
    path("api/metadata", views.metadata, name="metadata"),
    path("api/system/access", views.system_access, name="system_access"),
    path("api/system/actualization", views.system_actualization, name="system_actualization"),
    path("api/system/public-access", views.system_public_access, name="system_public_access"),
    path("api/gee/layers", views.gee_layers, name="gee_layers"),
    path("api/data/sources", views.data_catalog, name="data_catalog"),
    path("api/data/assets", views.data_assets, name="data_assets"),
    path("api/data/assets/upload", views.data_asset_upload, name="data_asset_upload"),
    path("api/data/assets/<uuid:asset_id>/download", views.data_asset_download, name="data_asset_download"),
    path("api/data/history/nasa-power", views.nasa_power_history, name="nasa_power_history"),
    path("api/data/intelligence/monthly", views.monthly_intelligence, name="monthly_intelligence"),
    path("api/data/intelligence/metrics", views.environmental_metrics, name="environmental_metrics"),
    path("api/data/research-context", views.research_context, name="research_context"),
    path("api/data/imagery/sentinel-2", views.sentinel_2_search, name="sentinel_2_search"),
    path("api/data/imagery/landsat/latest", views.landsat_latest, name="landsat_latest"),
    path("api/data/imagery/landsat/map", views.landsat_map, name="landsat_map"),
    path("api/data/soil/soilgrids", views.soilgrids_point, name="soilgrids_point"),
    path("api/auth/county-accounts", views.auth_county_accounts, name="auth_county_accounts"),
    path("api/auth/access-model", views.auth_access_model, name="auth_access_model"),
    path("api/auth/audit-log", views.auth_audit_log, name="auth_audit_log"),
    path("api/auth/validate-session", views.auth_validate_session, name="auth_validate_session"),
    path("api/auth/logout", views.auth_logout, name="auth_logout"),
    path("api/auth/register", views.auth_register, name="auth_register"),
    path("api/auth/login", views.auth_public_login, name="auth_public_login"),
    path("api/auth/google-login", views.auth_google_login, name="auth_google_login"),
    path("api/auth/forgot-password", views.auth_forgot_password, name="auth_forgot_password"),
    path("api/users", views.users_collection, name="users_collection"),
    path("api/users/<int:user_id>", views.user_detail, name="user_detail"),
    path("api/intelligence/status", views.intelligence_status, name="intelligence_status"),
    path("api/intelligence/query", views.intelligence_query, name="intelligence_query"),
    path("api/intelligence/insights", views.intelligence_insights, name="intelligence_insights"),
    path("api/jobs", views.processing_jobs, name="processing_jobs"),
    path("api/jobs/<uuid:job_id>", views.processing_job_detail, name="processing_job_detail"),
    path("api/reports", views.intelligence_reports, name="intelligence_reports"),
    path("api/reports/<int:report_id>", views.intelligence_report_detail, name="intelligence_report_detail"),
    path(
        "api/reports/<int:report_id>/transition",
        views.intelligence_report_transition,
        name="intelligence_report_transition",
    ),
    path(
        "api/reports/<int:report_id>/export/<str:export_format>",
        views.intelligence_report_export,
        name="intelligence_report_export",
    ),
    path("api/payments/config", views.payments_config, name="payments_config"),
    path("api/payments/mpesa/stk-push", views.payments_stk_push, name="payments_stk_push"),
    path("api/payments/mpesa/status", views.payments_status, name="payments_status"),
    path("api/payments/mpesa/callback", views.payments_mpesa_callback, name="payments_mpesa_callback"),
    path("api/alerts", views.operational_alerts, name="operational_alerts"),
    path("api/field-reports", views.field_reports, name="field_reports"),
    path("api/field-reports/<int:report_id>/verify", views.field_report_verify, name="field_report_verify"),
    path("api/data/quality", views.data_quality, name="data_quality"),
    path("api/boundary/counties", views.boundary_counties, name="boundary_counties"),
    path("api/boundary/county/<path:identifier>", views.boundary_county, name="boundary_county"),
    path("api/analysis/live/status", views.analysis_live_status, name="analysis_live_status"),
    path("api/analysis/country", views.analysis_country, name="analysis_country"),
    path("api/osm/metric/<str:topic>", views.osm_metric, name="osm_metric"),
    path("api/gee/metric/<str:topic>", views.gee_metric, name="gee_metric"),
    path("api/gee/status", views.gee_status, name="gee_status"),
    path("api/analysis/county/<path:identifier>", views.analysis_county, name="analysis_county"),
    path("api/analysis/subcounty/<path:identifier>", views.analysis_subcounty, name="analysis_subcounty"),
    path("api/analysis/ward/<path:identifier>", views.analysis_ward, name="analysis_ward"),
    path("api/analysis/area", views.analysis_area, name="analysis_area"),
    path("api/indices/evaluate", views.indices_evaluate, name="indices_evaluate"),
    path("api/automation/status", views.automation_status, name="automation_status"),
    path("api/segmentation/<str:segment_class>", views.segmentation, name="segmentation"),
    path("assets/<path:asset_path>", views.frontend_asset, name="frontend_asset"),
    path("data/<path:data_path>", views.frontend_data, name="frontend_data"),
    re_path(r"^(?P<request_path>.*)$", views.frontend_catchall, name="frontend_catchall"),
]
