# Generated by Django 5.2.15 on 2026-06-20 17:07

import aeis_dashboard.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeis_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to=aeis_dashboard.models.data_asset_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('asset_type', models.CharField(choices=[('vector', 'Vector GIS'), ('raster', 'Raster GIS'), ('tabular', 'Tabular'), ('archive', 'Archive')], max_length=16)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('scope_level', models.CharField(choices=[('national', 'National'), ('county', 'County'), ('subcounty', 'Sub-county'), ('ward', 'Ward'), ('farm', 'Farm')], default='national', max_length=20)),
                ('scope_name', models.CharField(blank=True, max_length=160)),
                ('scope_code', models.CharField(blank=True, max_length=40)),
                ('acquisition_start', models.DateField(blank=True, null=True)),
                ('acquisition_end', models.DateField(blank=True, null=True)),
                ('feature_count', models.PositiveIntegerField(blank=True, null=True)),
                ('geometry_types', models.JSONField(blank=True, default=list)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='ready', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_data_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('provider', models.CharField(max_length=120)),
                ('base_url', models.URLField()),
                ('source_type', models.CharField(choices=[('climate', 'Climate time series'), ('imagery', 'Satellite imagery'), ('vector', 'Vector GIS'), ('raster', 'Raster GIS'), ('registry', 'Registry'), ('other', 'Other')], default='other', max_length=20)),
                ('coverage_start', models.DateField(blank=True, null=True)),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('latest_available', models.DateField(blank=True, null=True)),
                ('requires_auth', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
