# Generated by Django 5.2.15 on 2026-06-22 06:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeis_dashboard', '0002_dataasset_externaldatasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeisuser',
            name='role',
            field=models.CharField(choices=[('county', 'County officer'), ('ministry', 'Ministry command officer'), ('analyst', 'National analyst'), ('field_officer', 'Field officer'), ('farmer', 'Farmer / user'), ('auditor', 'Auditor')], db_index=True, default='county', max_length=16),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('alert_type', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('scope_level', models.CharField(db_index=True, default='national', max_length=20)),
                ('scope_name', models.CharField(blank=True, db_index=True, max_length=160)),
                ('scope_code', models.CharField(blank=True, max_length=40)),
                ('geometry', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(default='low', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=160)),
                ('spatial_coverage', models.CharField(blank=True, max_length=240)),
                ('temporal_coverage', models.CharField(blank=True, max_length=240)),
                ('coordinate_reference_system', models.CharField(blank=True, max_length=120)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('warning', 'Warning'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('missing_data_warning', models.TextField(blank=True)),
                ('projection_warning', models.TextField(blank=True)),
                ('duplicate_warning', models.TextField(blank=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='aeis_dashboard.dataasset')),
            ],
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(default='field_observation', max_length=80)),
                ('county_name', models.CharField(db_index=True, max_length=100)),
                ('county_code', models.CharField(blank=True, max_length=8)),
                ('subcounty_name', models.CharField(blank=True, max_length=120)),
                ('ward_name', models.CharField(blank=True, max_length=120)),
                ('farm_reference', models.CharField(blank=True, max_length=160)),
                ('crop_type', models.CharField(blank=True, max_length=100)),
                ('observation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('observations', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_field_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(default='brief', max_length=80)),
                ('scope_level', models.CharField(db_index=True, default='national', max_length=20)),
                ('scope_name', models.CharField(blank=True, db_index=True, max_length=160)),
                ('scope_code', models.CharField(blank=True, max_length=40)),
                ('question', models.TextField(blank=True)),
                ('executive_summary', models.TextField()),
                ('key_observations', models.JSONField(default=list)),
                ('risk_areas', models.JSONField(default=list)),
                ('affected_areas', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('recommended_actions', models.JSONField(default=list)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=16)),
                ('explainability', models.TextField(blank=True)),
                ('data_sources', models.JSONField(default=list)),
                ('missing_data', models.JSONField(default=list)),
                ('provider', models.CharField(default='local_rule_based', max_length=40)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('report_type', models.CharField(db_index=True, default='intelligence_brief', max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('scope_level', models.CharField(db_index=True, default='national', max_length=20)),
                ('scope_name', models.CharField(blank=True, db_index=True, max_length=160)),
                ('scope_code', models.CharField(blank=True, max_length=40)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(blank=True, max_length=32)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('content', models.JSONField(default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(default='low', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='aeis_dashboard.intelligencereport')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
